// This file is automatically generated. Do not modify it.
import { FirebaseOptions } from 'firebase/app';

// This is the configuration for the Firebase project that will be used by the app.
// It is safe to expose this configuration to the client.
export const firebaseConfig: FirebaseOptions = JSON.parse(
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{}'
);
